name: CI

on:
  push:
  pull_request:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1

      - name: Set up uv
        uses: astral-sh/setup-uv@v10.0.1
        with:
          python-version: "3.11"
          enable-cache: true

      - name: Install dependencies
        run: uv sync --all-groups --frozen

      - name: Lint
        run: uv run ruff check .

      - name: Test
        run: uv run pytest

  build-and-push:
    needs: lint-test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    strategy:
      matrix:
        include:
          - service: intent-classifier
            dockerfile: src/services/intent_classifier/Dockerfile
          - service: retriever
            dockerfile: src/services/retriever/Dockerfile
          - service: response-generator
            dockerfile: src/services/response_generator/Dockerfile
          - service: ingestion
            dockerfile: src/ingestion/Dockerfile

    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1

      - name: Configure AWS Credentials for US East-1
        uses: aws-actions/configure-aws-credentials@v6.3.0
        if: github.ref == 'refs/heads/main'
        with:
          role-to-assume: ${{ vars.AWS_ECR_PUSH_ROLE_ARN }}
          aws-region: us-east-1

      - name: Login to AWS ECR
        uses: aws-actions/amazon-ecr-login@v2.1.7
        if: github.ref == 'refs/heads/main'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4.2.0

      - name: Build and push
        uses: docker/build-push-action@v7.3.0
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: ${{ github.ref == 'refs/heads/main'}}
          labels: org.opencontainers.image.source=https://github.com/${{ github.repository }}
          tags: |
            ${{ vars.ECR_REGISTRY }}/auto-safety-assist/${{ matrix.service }}:${{ github.sha }}
          cache-from: type=gha,scope=${{ matrix.service }}
          cache-to: type=gha,mode=max,scope=${{ matrix.service }}
